### ISSUE TITLE
Classnotfound exception

### ISSUE THREAD

**Issue by aghorpade** [authorjapps/zerocode-hello-world#20]
Hi team,

I am facing issue while running a hello world test case..

`10:13:16,764 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
10:13:16,780 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@a097cc - Registering current configuration as safe fallback point

2019-07-29 10:13:16,951 [main] INFO org.jsmart.zerocode.core.utils.RunnerUtils - ### testClass : class com.group.qa.unittest.hopewiser

java.lang.NoClassDefFoundError: com/aventstack/extentreports/ExtentReports

	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethods(Class.java:1975)
	at com.google.inject.spi.InjectionPoint.getInjectionPoints(InjectionPoint.java:688)
	at com.google.inject.spi.InjectionPoint.forInstanceMethodsAndFields(InjectionPoint.java:380)
	at com.google.inject.internal.ConstructorBindingImpl.getInternalDependencies(ConstructorBindingImpl.java:164)
	at com.google.inject.internal.InjectorImpl.getInternalDependencies(InjectorImpl.java:613)
	at com.google.inject.internal.InjectorImpl.cleanup(InjectorImpl.java:569)`

**Comment by authorjapps** [comment]
Hey @aghorpade , the latest HelloWorld build status is `PASS`.

See the CI build here(build No. 26): https://travis-ci.org/authorjapps/zerocode-hello-world

It looks like you are trying to run some other HelloWorld build. Can you share your repo details or POM details if possible?

I would suggest, just clone this `HelloWorld` repo and once you run it well, then just copy the `maven dependency` to your own repo. That's an easy approach I guess. 👍 

Clone url and commend below:
```
git clone https://github.com/authorjapps/zerocode-hello-world.git
```

**Comment by aghorpade** [comment]
There was issue with dependency download in vpn due to which it was failing. Now i got it working.
